- block:
   - name: perform system update
     ansible.builtin.dnf:
       name: "*"
       state: latest
     become: true
   - name: install base productivity tools
     ansible.builtin.dnf:
       name: "{{ base_productivity_tools }}"
       state: latest
     become: true
