
---
- block:
  - name: Enable a specific COPR repository
    community.general.copr:
      name: dejan/lazygit
      state: enabled
    become: true
  - name: Install lazygit
    community.general.rpm_ostree_pkg:
      name: lazygit
      state: present
    become: true
